# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform :android

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build"
  lane :build do
    gradle(task: "clean assembleRelease")
  end

	desc "Build debug and test APK for screenshots"
	lane :build_for_screengrab do
		gradle(task: 'clean')
		gradle(
			task: 'assemble',
			build_type: 'Debug'
		)
		gradle(
			task: 'assemble',
			build_type: 'AndroidTest'
		)
	end

	desc "Submit a new Beta Build to Firebase App Distribution"
	lane :beta do
		build

		firebase_app_distribution(
			app: "1:1234567890:android:0a1b2c3d4e5f67890",
			groups: "group-two",
			release_notes: "Lots of amazing new features to test out!",
		)
	end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(release_status: "draft")
  end
end
